% !Rnw weave = knitr

<<setup-child, include = FALSE, echo=FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb_coll.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-trees.tex}

\kopf{Information Theory}

\tableofcontents

% ------------------------------------------------------------------------------
% LECTURE EXERCISES
% ------------------------------------------------------------------------------

\dlz
\exlect
\lz

\aufgabe{Entropy}{
	<<child="ex_rnw/ex_some_information.Rnw">>=
	@
}

\dlz

\aufgabe{Kullback-Leibler Divergence}{
	<<child="ex_rnw/ex_kld_binom_normal.Rnw">>=
	@
}



\aufgabe{The Convexity of KL Divergence}{
	<<child="ex_rnw/ex_kld_convexity.Rnw">>=
	@
}

\aufgabe{Mutual Information of Three Variables}{
	<<child="ex_rnw/ex_mutualinfo_three_var.Rnw">>=
	@
}

\aufgabe{Smoothed Cross-Entropy Loss}{
	<<child="ex_rnw/ex_smoothed_crossentropy.Rnw">>=
	@
}

% 
% % ------------------------------------------------------------------------------
% % PAST EXAMS
% % ------------------------------------------------------------------------------
% 
% \dlz
% \exexams
% \lz
% 
% \aufgabeexam{WS2020/21}{first}{1}{
% foo
% }
% 
% \dlz
% \loesung{
% bar
% }
% 
% % ------------------------------------------------------------------------------
% % INSPO
% % ------------------------------------------------------------------------------
% 
% \dlz
% \exinspo