% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopfsl{}{Information Theory}


\aufgabe{Kullback-Leibler Divergence}{
	<<child="ex_rnw/ex_kld_binom_normal.Rnw">>=
	@
}

\aufgabe{The Convexity of KL Divergence}{
	<<child="ex_rnw/ex_kld_convexity.Rnw">>=
	@
}



