% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopfsl{4}{Information Theory}




\loesung{Kullback-Leibler Divergence}{
	<<child="ex_rnw/sol_kld_binom_normal.Rnw">>=
	@
}


\loesung{The Convexity of KL Divergence}
	<<child="ex_rnw/sol_kld_convexity.Rnw">>=
	@
