% !Rnw weave = knitr

<<setup-child, include = FALSE, echo=FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb_coll.Rnw")
@


\kopf{Multiclass Classification}

\tableofcontents

% ------------------------------------------------------------------------------
% LECTURE EXERCISES
% ------------------------------------------------------------------------------

\dlz
\exlect
\lz

\aufgabe{Multiclass and Softmax Regression}{
<<child="ex_rnw/ex_softmax_mnist.Rnw">>=
@
}

\dlz

\aufgabe{Logistic Regression, Softmax, Cross-Entropy}{
<<child="ex_rnw/ex_lt_softmax_theory_wo_mlr.Rnw">>=
@
}

\dlz

\aufgabe{Multiclass Hinge Loss}{
<<child="ex_rnw/ex_multiclass_hinge_loss.Rnw">>=
@
}

\dlz

\aufgabe{Multiclass Classification with 0-1-Loss}{
<<child="ex_rnw/ex_multiclass_01loss.Rnw">>=
@
}




% 
% % ------------------------------------------------------------------------------
% % PAST EXAMS
% % ------------------------------------------------------------------------------
% 
% \dlz
% \exexams
% \lz
% 
% % \aufgabeexam{WS2020/21}{first}{1}{
% % foo
% % }
% % 
% % \dlz
% % \loesung{
% % bar
% % }
% 
% % ------------------------------------------------------------------------------
% % INSPO
% % ------------------------------------------------------------------------------
% 
% \dlz
% \exinspo