% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-svm.tex}
\input{../../latex-math/ml-gp.tex}

\kopficsl{11}{Support Vector Machines}

\loesung{Hard Margin Classifier}{
	<<child="ex_rnw/sol_svm_kernel_definition.Rnw">>=
	@
}


