% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-svm.tex}
\input{../../latex-math/ml-gp.tex}

\kopfsl{}{Linear SVM}

\loesung{Soft Margin Classifier}{
	<<child="ex_rnw/sol_linsvm_softmargin.Rnw">>=
	@
}
\dlz

\loesung{Optimization}{
	<<child="ex_rnw/sol_linsvm_subgradient.Rnw">>=
	@
}
