% !Rnw weave = knitr

<<setup-child, include = FALSE, echo=FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb_coll.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-ensembles.tex}

\kopf{Gradient Boosting}

\tableofcontents

% ------------------------------------------------------------------------------
% LECTURE EXERCISES
% ------------------------------------------------------------------------------

\dlz
\exlect
\lz

\aufgabe{Boosting - Empirical Risk}{
	<<child="ex_rnw/ex_boosting_empirical_risk.Rnw">>=
	@
}
\aufgabe{Boosting - Stumps}{
	<<child="ex_rnw/ex_boosting_stumps.Rnw">>=
	@
}

\aufgabe{Boosting - Updates}{
	<<child="ex_rnw/ex_boosting_updates.Rnw">>=
	@
}

% % ------------------------------------------------------------------------------
% % PAST EXAMS
% % ------------------------------------------------------------------------------
% 
\dlz
\exexams
\lz
% 
\aufgabeexam{Exam 2020}{}{1}{
	<<child="ex_rnw/ex_boosting_exam_2020.Rnw">>=
	@
}
% 
% \dlz
% \loesung{
% bar
% }
% 
% % ------------------------------------------------------------------------------
% % INSPO
% % ------------------------------------------------------------------------------
% 
% \dlz
% \exinspo