% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-ensembles.tex}
\input{../../latex-math/ml-trees.tex}

\kopficsl{}{Boosting}



\aufgabe{AdaBoost - Updates}{
	<<child="ex_rnw/ex_boosting_updates.Rnw">>=
	@
}
\lz

\aufgabe{AdaBoost - Decision Stump}{
	<<child="ex_rnw/ic_boosting_stumps.Rnw">>=
	@
}
\lz