% !Rnw weave = knitr

<<setup-child, include = FALSE, echo=FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb_coll.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-ensembles.tex}
\input{../../latex-math/ml-trees.tex}

\kopf{Gradient Boosting}

\tableofcontents

% ------------------------------------------------------------------------------
% LECTURE EXERCISES
% ------------------------------------------------------------------------------

\dlz
\exlect
\lz

\aufgabe{VC Dimension 1}{
	<<child="ex_rnw/ex_vc_dimension_1.Rnw">>=
	@
}
\aufgabe{VC Dimension 2}{
	<<child="ex_rnw/ex_vc_dimension_2.Rnw">>=
	@
}


% % ------------------------------------------------------------------------------
% % PAST EXAMS
% % ------------------------------------------------------------------------------
% 
\dlz
\exexams
\lz
% 
% \aufgabeexam{Exam 2020}{}{1}{
% 	<<child="ex_rnw/ex_boosting_exam_2020.Rnw">>=
% 	@
% }
% 
% \dlz
% \loesung{
% bar
% }
% 
% % ------------------------------------------------------------------------------
% % INSPO
% % ------------------------------------------------------------------------------
% 
% \dlz
% \exinspo