The polynomial kernel is defined as
$$
k(\xv, \tilde{\xv}) = (\xv^\top \tilde{\xv} + b)^d.
$$
Furthermore, assume $\xv \in \mathbb{R}^2$ and $d = 2$.

\begin{enumerate}

  \item
    Derive the explicit feature map $\phi$ taking into account that the following equation holds:
    $$
    k(\xv, \tilde{\xv}) = \langle \phi(\xv), \phi(\tilde{\xv}) \rangle
    $$

  \item
    Describe the main differences between the kernel method and the explicit feature map.

\end{enumerate}
